# netlify.toml
[build]
command = "npm run build"
publish = "dist"

[dev]
command = "vite"
port = 5173

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' https://unpkg.com https://*.clerk.com https://*.clerk.dev;
      style-src 'self' 'unsafe-inline' https://unpkg.com https://*.clerk.com https://*.clerk.dev;
      connect-src 'self' https://*.clerk.com https://*.clerk.dev;
      font-src 'self' https://unpkg.com;
      img-src 'self' data: https:;
      frame-src https://*.clerk.com https://*.clerk.dev;
    """
